---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(rstan)
library(mvtnorm)
library(MASS)
library(tidyverse)
```

```{r}
set.seed(1)
n <- 100
prop <- rep(1/3, 3)
u <- runif(n)

x <- (u < 1/3) * rmvnorm(n, c(-1, -1), .1 * diag(2)) +
     (1/3 < u) * (u < 2/3) * rmvnorm(n, c(2, 2), .3 * diag(2)) +
     (u > 2/3) * rmvnorm(n, c(2, -3), .5 * diag(2))

x %>% as_data_frame() %>%
  ggplot(aes(x = V1, y = V2)) +
  geom_density_2d()  
```

```{r}
mixture_data = list(N = n, D = 2, K = 3, y = x)

mixture_model<-'
data {
 int D; //number of dimensions
 int K; //number of gaussians
 int N; //number of data
 vector[D] y[N]; //data
}

parameters {
 simplex[K] theta; //mixing proportions
 ordered[D] mu[K]; //mixture component means
 cholesky_factor_corr[D] L[K]; //cholesky factor of covariance
}

model {
 real ps[K];
 
 for(k in 1:K){
 mu[k] ~ normal(0,3);
 L[k] ~ lkj_corr_cholesky(4);
 }
 

 for (n in 1:N){
 for (k in 1:K){
 ps[k] = log(theta[k])+multi_normal_cholesky_lpdf(y[n] | mu[k], L[k]); //increment log probability of the gaussian
 }
 target += log_sum_exp(ps);
 }

}'

mixture_data = list(N = n, D = 2, K = 3, y = x)

fit = stan(model_code = mixture_model, data = mixture_data, iter = 5000, 
           warmup = 1000, chains = 1)
```

