---
title: "Normal Inverse Gamma model"
author: "Patrick Ding, James Dole, Naveed Merchant"
output: github_document
---

## Normal inverse gamma

$$
\begin{aligned}
x_1 \ldots x_n|\mu &\sim N(\mu, \sigma^2)
\\
\pi(\mu, \sigma^2) &\propto \frac{1}{\sigma^2}
\\
\mu, \sigma^2 | x_1 \ldots x_n &\sim 
  N\text{-}\Gamma^{-1}(\tau = \bar{x}, \lambda = n, 
  \alpha = (n+4)/2, \beta = \frac{1}{2}(\sum x_i^2 - n\bar{x}^2))
\\
\sigma^2|x_1 \ldots x_n &\sim \Gamma^{-1}(\alpha, \beta)
\\
\mu | x_1 \ldots x_n &\sim t_{2\alpha}\big(\tau, \beta/(\alpha\lambda)\big
\end{aligned}
$$

```{r}
dnig <- function(m, v, mu, lambda, alpha, bet) {
  sqrt(lambda / 2 * pi * v) * 
    ((bet ^ alpha) / (gamma(alpha))) * v ^ (- alpha - 1) *
    exp(- (2 * bet + lambda * (m - mu) ^ 2) / (2 * v ^ 2))
}
```

```{r warning=FALSE}
source("nig.R")
source("utility.R")
source("hmc.R")
source("metropolis_hastings.R")
source("gibbs.R")
library(ggplot2)
library(MCMCpack)
library(invgamma)
set.seed(1)

n <- 200
S <- 10000

x <- rnorm(n, 0, 5)
tau <- mean(x)
lambda <- n
alpha <- (n + 4) / 2
bet <- .5 * (sum(x ^ 2) - n * mean(x) ^ 2)

mu_mh_s <- 2
sigma_mh_s <- 10
nig_lik <- nig_likelihood(x)
nig_p <- nig_prior()
nig_prop <- nig_proposal(mu_mh_s, sigma_mh_s)
nig_prop_d <- nig_prop_density(mu_mh_s, sigma_mh_s)

nig_pot <- nig_U(x)
nig_grad <- nig_dU(x)

nig_mh <- metropolis_hastings(param_init = list(1, 10), 
                              likelihood = nig_lik, 
                              prior = nig_p, 
                              proposal = nig_prop, 
                              prop_density = nig_prop_d,
                              iters = S)
nig_gibbs <- gibbs(list(1, 10), S, nig_cond_mu(x), nig_cond_sigma(x))
nig_hmc <- hmc(param_init = c(1, 10), nig_pot, nig_grad, 
               .05, 50, S)

```

```{r}
plot_grid <- seq(-4, 4, .01)
hist(nig_mh$samples[[1]][101:S, ], probability = TRUE, breaks = 100)
lines(plot_grid, 
      dt(sqrt(alpha * lambda / bet) * (plot_grid - tau) , df = 2 * alpha))

plot_grid <- seq(.01, 50, .01)
hist(nig_mh$samples[[2]][101:S, ], probability = TRUE, breaks = 25)
lines(plot_grid, dinvgamma(plot_grid, alpha, bet))

plot_grid <- seq(-4, 4, .01)
hist(nig_gibbs$samples[[1]], breaks = 25, probability = TRUE)
lines(plot_grid, 
      dt(sqrt(alpha * lambda / bet) * (plot_grid - tau), df = 2 * alpha))

plot_grid <- seq(0, 60, .1)
hist(nig_gibbs[, 2], breaks = 25, xlim = c(0, 100), probability = TRUE)
lines(plot_grid, dinvgamma(plot_grid, alpha, bet))
```

## compare posterior means

```{r}
mh_mu <- mcmc(nig_mh$samples[[1]][1001:(S-1)])
gibbs_mu <- mcmc(nig_gibbs$samples[[1]][1001:(S-1)])
hmc_mu <- mcmc(nig_hmc$samples[1001:(S-1), 1])

mh_sigma <- mcmc(nig_mh$samples[[2]][1001:(S-1)])
gibbs_sigma <- mcmc(nig_gibbs$samples[[2]][1001:(S-1)])
hmc_sigma <- mcmc(nig_hmc$samples[1001:(S-1), 2])

post_mus <- 
  data_frame(mh = mh_mu, gibbs = gibbs_mu, hmc = hmc_mu) %>%
  mutate(type = "mean") %>%
  mutate(iter = row_number()) %>%
  gather(key = method, value = sample, -iter, -type)
post_sigmas <- 
  data_frame(mh = mh_sigma, gibbs = gibbs_sigma, hmc = hmc_sigma) %>%
  mutate(type = "var") %>%
  mutate(iter = row_number()) %>%
  gather(key = method, value = sample, -iter, -type)
posts <- rbind(post_mus, post_sigmas)
  
nig_trace <- ggplot(posts, aes(x = iter, y = sample)) +
  geom_path() +
  facet_grid(type ~ method, scales = "free")
ggsave(plot = nig_trace, filename = "images/nig_trace.png", device = "png",
       scale = .6)

post_tab <- c("MH" = effectiveSize(mh_mu),
  "Gibbs" = effectiveSize(gibbs_mu),
  "HMC" = effectiveSize(hmc_mu)) %>%
  knitr::kable(format = "latex", digits = 1,
               col.names = "Effective Sample Size")

plot_grid <- seq(10, 40, .01)
true_sigma <- data_frame(x = plot_grid, y = dinvgamma(plot_grid, alpha, bet))
nig_sigma_dens <- post_sigmas %>%
  ggplot(aes(x = sample)) +
    geom_path(data = true_sigma, aes(x, y), color = "blue") +
    geom_density() +
    facet_wrap(~ method) +
    labs(x = "x", y = "density")
ggsave(plot = nig_sigma_dens, filename = "images/nig_dens.png", device = "png",
       width = 7, height = 4)
               
acf(mh_mu)
acf(gibbs_mu)
acf(hmc_mu)
```

